### ISSUE TITLE
How to use bilinear model v1.6?

### ISSUE THREAD

**Issue by XPandora** [yanght321/Detailed3DFace#10]
Thanks for your great work first! I notice that you have made your bilinear model v1.6 public. However, I did not found any file that corresponds to the 'core_847_50_52.npy' as stated in your instruction. Can you please tell me how to use your bilinear model v1.6 for this code?

**Comment by zhuhao-nju** [comment]
I am sorry that this project only works for bilinear model v1.3, as I don't have time to update it......  We are moving forward and will use V1.6 for future work.
