### ISSUE TITLE
测试结果不理想

### ISSUE THREAD

**Issue by yfji** [yanght321/Detailed3DFace#11]
HI，您好，很感谢你们杰出的工作！我使用您提供的拟合代码进行了测试，发现生成的mesh并不能很有效的反映皱纹信息，测试图像如下（上面是拟合结果，下面是texture），最终的vertices数量是787026，三角形数量是1570624。能帮忙分析一下哪儿出问题了吗？万分感谢！
![image](https://user-images.githubusercontent.com/27565508/116362586-c9a91800-a834-11eb-8eb6-63a1a34187dd.png)
![image](https://user-images.githubusercontent.com/27565508/116362591-cada4500-a834-11eb-8b7f-ed8041f571fc.png)

**Comment by zhuhao-nju** [comment]
我们的结果以base mesh+displacement map的形式保存出来，看起来你只渲染了前者，只能够表现粗略细节。要渲染细节效果需要使用支持displacement map的软件，如3D max，MAYA等。我们的代码中也包含简略的displacement渲染，会自动保存出渲染图片。
