### ISSUE TITLE
predict obj result

### ISSUE THREAD

**Issue by luoww1992** [yanght321/Detailed3DFace#13]
![image](https://user-images.githubusercontent.com/45957595/122381648-bc3e1d80-cf9b-11eb-9a17-d9fc0ac983ca.png)

when i run the code, 
the result obj shows like img 2--like the base;
and with --render , the render img likes img 1,  it looks very good !

so how to get the predicted detail obj result like img 3 ?

**Comment by luoww1992** [comment]
i use the default code and settings to run it, my results like:
![image](https://user-images.githubusercontent.com/45957595/122394669-d29ea600-cfa8-11eb-8066-4d42f63a428a.png)

![image](https://user-images.githubusercontent.com/45957595/122394716-ddf1d180-cfa8-11eb-8b76-85405a2c05af.png)

1-- input_image
2--predict obj
3--render.jpg with --render

how to get the predicted detail obj result like img 3 ?

**Comment by luoww1992** [comment]
there are my test images:
![000087](https://user-images.githubusercontent.com/45957595/122493564-7ffdd200-d01a-11eb-8922-fa95e3cfb9a3.png)
![000089](https://user-images.githubusercontent.com/45957595/122493573-82f8c280-d01a-11eb-9371-b1c39c1d4f6d.png)

**Comment by luoww1992** [comment]
@ @yanght321 
i see there is v1.6 model,
how to get a 3Dface with v1.6 bilinear model.

**Comment by zhuhao-nju** [comment]
Hi, our results consist of a base mesh (that obj model) and a displacement map (can be saved as PNG).  Image 2 is only rendering base mesh, and image 3 is rendering base mesh together with displacement map.  You may use softwares that support displacement map to render image 3, like Zbrush, 3D max, maya, KeyShot.

Sorry that this project only works for bilinear model v1.3, and I don't have time to update it.  We are moving forward and will use V1.6 for future work.
