### ISSUE TITLE
How to calculate the point-to-plane reconstruction error

### ISSUE THREAD

**Issue by Bornblack** [yanght321/Detailed3DFace#15]
Hi,

I want to test some other 3d face reconstruction methods on the FaceScape dataset. 
As the predicted meshes from different methods are in different coordinate systems , how can I align the predicted meshes to the groud truth meshes?
Can you share the code to calculate the  point-to-plane reconstruction error as the paper mentioned ?

Also,  Can you share some tips about how to draw the error heatmap like below? I find there is no much reference code.

![image](https://user-images.githubusercontent.com/49244832/142226432-26554123-6da3-45b1-84be-487583551a68.png)

Any help would be appreciated! :kissing_heart:

**Comment by zhuhao-nju** [comment]
Hi, here is a solution to evaluate methods in different coordinate systems:

https://github.com/zhuhao-nju/facescape/tree/master/benchmark

And here is the heat mesh rendering part:

https://github.com/zhuhao-nju/facescape/blob/dd9ecc75eb0292cb46960c441eb744fdbbecf11b/benchmark/code/evaluator.py#L251
