### ISSUE TITLE
如何从core_tensor [:50, :52, :78951]里面提取 mean shape，identity blendshape, expression blendshape 

### ISSUE THREAD

**Issue by JunHanStudy** [yanght321/Detailed3DFace#2]
平时用BFM或Face Warehouse人脸模型时候，都是有现成的 meanshape, 身份 blendshape (身份basis个数 * 顶点)，表情blendshape (表情base个数 * 顶点)。如何从(50, 52, 78951)这里提取出 20个身份 blendshape呢？我可否用 [:50, 0, :78951] 做下PCA就得到了身份basis 呢。对于mean shape，是这里做完的PCA的第一个吗？谢谢大佬奠基性工作~

**Comment by yanght321** [comment]
你好，
  BFM提供的PCA模型，表情blendshape是和id没有关系的，就是对所有id，表情的basis都是一样的。而我们的bilinear
model里面，表情的blendshape是随id确定的，所以这样表情上应该会比BFM表达能力更强（但是模型也更大）。另外， Face
Warehouse原始提供的应该也是类似我们这种bilinear model吧。
  要从我们的模型得到BFM那种模型的话，可以简单地分别用factors_id.npy里面每个人的id系数，从bilinear
model得到每个人的3D顶点，然后做PCA得到身份basis 。表情basis可以用所有人对应表情blendshape的平均。关于mean
shape，PCA算法本身就要求输入数据是0均值的，所以要先求个平均得到mean shape。做PCA之前要先减mean
shape，得到的就是basis。

**Comment by JunHanStudy** [comment]
因为这里的数据是[:50, :52, :78951], 乘以每个人的id系数可以得到同一个人52个不同表情的3D顶点。为了得到身份basis，算PCA的时候是利用不同人的neutral表情数据？谢谢大佬啦~

**Comment by yanght321** [comment]
如果所有表情一起算PCA，得到的basis里面id和表情就混在一起了。具体怎么算要看你用途吧。

**Comment by JunHanStudy** [comment]
谢谢大佬~ 用你说的方法计算出来的身份basis和 BFM的身份basis前几个可视化对比了下，结果合理。根据factors_id.npy，我们可以得到所有人对应同一个表情的3D顶点。 “表情basis可以用所有人对应表情blendshape的平均”，你这里说的表情blendshape如何得到呢？表情basis用所有人对应表情的3D顶点的平均减去mean shape，应该是这样不

**Comment by YunjieYu** [comment]
首先膜拜下大佬的精彩工作与对话~请教一下，对于core_tensor[50, **0**, 78951]，其中索引**0**代表的是neutral表情吗？我可视化了之后发现人脸的嘴巴没有闭合，对于中性表情来说，请问这是正常现象吗？
期待回复！~谢谢

**Comment by YunjieYu** [comment]
@yanght321 @JunHanStudy 首先膜拜下大佬的精彩工作与对话~请教一下，对于core_tensor[50, 0, 78951]，其中索引0代表的是neutral表情吗？我可视化了之后发现人脸的嘴巴没有闭合，对于中性表情来说，请问这是正常现象吗？
期待回复！~谢谢
