### ISSUE TITLE
Question in section 4.1 Base model fitting

### ISSUE THREAD

**Issue by yihu-dev** [yanght321/Detailed3DFace#3]
Hi, 

Thank you for your awesome paper and code. 
I have few questions related to base model fitting.

1. Photometric loss. When looking into your code, the bilinear_model, I found that the base model fitting part is not as same as described in your paper which suppose to combine pixel-level consistency and regularizations. 

2. Landmark loss. Another part is the landmark detector as you mentioned. I wonder how much the performance will degrade using dlib's algorithm. I've tried dlib's, and FAN-2d. both are not very accurate and thus affects the model fitting.

I'm thinking of using FAN detector and  differentiable rendering (pytorch3d) to do base model fitting. I've tried model fitting using Basel face model using pytorch3d, but it's very difficult to control the lambdas-{id, exp, alb} of regularization terms. 
The bilinear model looks better than BFM. I would like to know more details about the model fitting.

In other case, If I use an inaccurate base model fitting, do I need to re-prepare deforming maps and others to re-train pix2pixHD.

Thanks.
Huyi

**Comment by Bornblack** [comment]
@zhuhao-nju @yanght321 
Same question.
The Pixel Level Consistency is not implemented in the Base Model Fitting part. Is it relevant to the license issue?
It could be really helpful if you can share the pixel-level consistency fitting code.
