### ISSUE TITLE
pygame.error: No available video device

### ISSUE THREAD

**Issue by JaniceXiong** [yanght321/Detailed3DFace#5]
When the program run to render.py，
srf = pygame.display.set_mode(viewport, pygame.OPENGL | pygame.DOUBLEBUF)
I meeted the error "pygame.error: No available video device". I searched for a lot of solutions like "os.environ["SDL_VIDEODRIVER"] = "dummy", but raised another error "pygame.error: OpenGL not available" .

I installed all the packages as requirements.txt, could anyone give any advice to fix this problem?

**Comment by cenalzw** [comment]
@JaniceXiong Hello! Did you fix this problem? I got the same issue with you and I have no idea to fix it. Hope you can help me. Thanks a lot!

**Comment by liurunxing13** [comment]
Maybe you use ssh serviece to connect linux server, you can try mobile xterm or other software which support X11 to run main.py.
