### ISSUE TITLE
Pygame save  a black image

### ISSUE THREAD

**Issue by a78239636** [yanght321/Detailed3DFace#6]
I can see correct result from pygame( face with model),  but during save step, I just got a black image. Thanks for your contrubution,  hope you can give me some advice.
In renderer.py :
```
        pygame.display.flip()
        pygame.image.save(srf, out_path)  
```

**Comment by gobigrassland** [comment]
l had the same problem

**Comment by jiaxiangshang** [comment]
I meet the same problem..

**Comment by jiaxiangshang** [comment]
I meet the same problem, can you give some suggestions? @gobigrassland @a78239636

**Comment by gerwang** [comment]
I solved the problem via the following code:
```python
        pygame.display.flip()
        np_img = np.zeros((viewport[1], viewport[0], 3), dtype=np.uint8)
        glReadPixels(0, 0, viewport[0], viewport[1], GL_BGR, GL_UNSIGNED_BYTE, np_img.data)
        np_img = np.ascontiguousarray(np_img[::-1])
        cv2.imshow('frame', np_img)
        cv2.waitKey(0)
        pygame.quit()
```
I know nothing about pygame, but I find that pygame seems only to provide an OpenGL context, therefore I use naive OpenGL API `glReadPixels` to take screenshot.

**Comment by jiaxiangshang** [comment]
@gerwang really helpful, thanks

**Comment by zhaozhibo234** [comment]
@gerwang really helpful!!!!!

**Comment by Bornblack** [comment]
Following code works for me on windows:
```Python
size = srf.get_size()
buffer = glReadPixels(0, 0, *size, GL_RGBA, GL_UNSIGNED_BYTE)

pygame.display.flip()

screen_surf = pygame.image.fromstring(buffer, size, "RGBA", True)  # flipped = True
pygame.image.save(screen_surf, out_path)
pygame.quit()
```

Reference：
https://stackoverflow.com/questions/66209365/how-to-save-pygame-scene-as-jpeg
