### ISSUE TITLE
Bilinear model  ver 1.3

### ISSUE THREAD

**Issue by wx176** [yanght321/Detailed3DFace#9]
Hello! Thanks for sharing your grate work! Would you please provide a link for Bilinear model ver 1.3 download? This will make it more convenient for us to evaluate this work. Since i saw the Bilinear model ver 1.6 has an external link. So i put forward this proposal :)

**Comment by zhuhao-nju** [comment]
I am sorry that this project only works for bilinear model v1.3, and I don't have time to update it...  We are moving forward and will use V1.6 for future work.  

To download v1.3, you still need to send request following the instructions in https://facescape.nju.edu.cn/.
